---
default: true

# Allow long lines (tables/URLs)
MD013: false

# Allow inline HTML (used for README table styling)
MD033: false

# Heading style: atx (#)
MD003:
  style: atx

# Trailing spaces allowed in code blocks only
MD009:
  strict: true

# Allow fenced code blocks without language if needed
MD040: false

# Do not require blank line before lists in tighter docs
MD032: false

# Allow inline HTML tables and relaxed table rules
MD034: false

#ul-style Unordered list style - allow both `*` and `-`
MD004: false
